apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api
  annotations:
    - foo: bar
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: recipe-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "150m"
