apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: recipe-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"