apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: recipe-api
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://dev.nabhan.xyz:6443
      - cluster: prod
        url: https://10.1.1.30:6443
  template:
    metadata:
      name: '{{cluster}}-busybox'
    spec:
      project: default
      source:
        repoURL: https://github.com/nabhanxyz/argocd.git
        targetRevision: HEAD
        path: applications/busybox/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: busybox