apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nats
spec:
  generators:
    - list:
        elements:
      - cluster: dev
        url: https://dev.nabhan.xyz:6443
      - cluster: prod
        url: https://10.1.1.30:6443
  template:
    metadata:
      name: nats-{{cluster}}
    spec:
      destination:
        namespace: nats
        server: "{{url}}"
      project: default
      source:
        path: applications/busybox/overlays/{{cluster}}
        repoURL: https://github.com/nabhanxyz/argocd.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        retry:
          limit: 5
        syncOptions:
          - CreateNamespace=true
