apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: nats
spec:
  project: default
  source:
    chart: nats/nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: develop
    helm:
      releaseName: 1.16.1
      valueFiles:
        - ../applications/nats/dev/values.yaml
  destination:
    server: "https://dev.nabhan.xyz:6443"
    namespace: nats
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 15m
      limit: 3
    syncOptions:
      - CreateNamespace=true
